src/Entity/Product.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;



/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable()

 */
class Product
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="description", type="text", length=65535, nullable=true)
     */
    private $description;

    /**
     * @var string|null
     *
     * @ORM\Column(name="picture", type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture")
     */
    private $imageFile;

    /**
     * @var int|null
     *
     * @ORM\Column(name="price", type="integer", nullable=true)
     */
    private $price;

    /**
     * @var int|null
     *
     * @ORM\Column(name="storage", type="integer", nullable=true)
     */
    private $storage;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }
    public function getFormattedPrice()
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getStorage(): ?int
    {
        return $this->storage;
    }

    public function setStorage(?int $storage): self
    {
        $this->storage = $storage;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Product
     */
    public function setImageFile(?File $imageFile): Product
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('storage')
            ->add('imageFile', FileType::class, [
                'required' => false
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/Particular/ProductController.php
<?php


namespace App\Controller\Particular;


use App\Entity\Basket;
use App\Entity\Product;
use App\Entity\ProductSearch;
use App\Form\BasketType;
use App\Form\ProductSearchType;
use App\Form\ServiceSearchType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class ProductController extends AbstractController
{
    /**
     * @var ProductRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(ProductRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }


    /**
     * @Route("/product", name="product.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {

        $search = new ProductSearch();
        $form = $this->createForm(ProductSearchType::class, $search);
        $form->handleRequest($request);


        $products = $paginator->paginate(
            $this->repository->findAllVisible($search),
            $request->query->getInt('page', 1), 12
        );
        return $this->render('product/index.html.twig', [
            'current_menu' => 'product',
            'products' => $products,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/product/{slug}-{id}", name="product.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Product $product, string $slug, Request $request, UserInterface $user): Response
    {
        $basket = new Basket();
        $basket->setIdProduct($product)
                ->setUserId($user);
        $form = $this->createForm(BasketType::class, $basket);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($basket);
            $this->em->flush();
            $this->addFlash('success', 'Produit bien ajouté au panier');
            return $this->redirectToRoute('basket.index', [
                'id' => $product->getId(),
                'basket'=> $basket,
                'slug' => $product->getSlug()
            ]);
        }
        if ($product->getSlug() == $slug) {
            return $this->render('product/show.html.twig', [
                'id' => $product->getId(),
                'slug' => $product->getSlug(),
                'product' => $product,
                'basket' => $basket,
                'form' => $form->createView()
            ]);
        }



    }
}

templates/product/_product.html.twig
<div class="card mb-4">
    {% if product.picture %}
        <img src="{{ vich_uploader_asset(product, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">

    {% else %}
        <img src="{{ 'images/products/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('product.show', {slug: product.slug, id: product.id}) }}">
                {{ product.name }}
            </a>
        </h5>

        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ product.formattedPrice }} €
        </div>
    </div>
</div>

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos produits' %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.name) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-success">Rechercher</button>
                    </div>

                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h1>Nos produits</h1>

        <div class="row">

            {% for product in products %}
                <div class="col-md-4">
                    {% include 'product/_product.html.twig' %}
                </div>

            {% endfor %}
        </div>

        <div class="pagination">
            {{ knp_pagination_render(products) }}
        </div>
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}


{% block title product.name %}

{% block body %}
    <div class="jumbotron">
        <div class="container">


            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}


            <div class="row">
                <div class="col-md-8">
                    {% if product.picture %}
                        <img src="{{ vich_uploader_asset(product, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto">

                    {% else %}
                        <img src="{{ 'images/products/empty.jpg' | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ product.name }}</h1>
                    <h2>Stockage: {{ product.storage }} pièces</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold">{{ product.formattedPrice }}€
                    </div>
                    {{ form_start(form) }}
                    {{ form_row(form.quantity) }}
                    <button class="btn btn-success">{{ button|default('Ajouter au panier') }}</button>
                    {{ form_end(form) }}

                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <p>
            {{ product.description | nl2br }}
        </p>
    </div>

{% endblock %}